import type { Theme } from 'theme-ui';

/**
 * SecretShare design tokens.
 *
 * Values are taken from the approved design canvas ("Foundations" artboard).
 * Breakpoint indices used throughout the app:
 *   array index 0 = base / mobile (<768px)
 *   array index 1 = >= 48em (768px)
 *   array index 2 = >= 64em (1024px)
 *   array index 3 = >= 80em (1280px)
 *
 * fontSizes index map (used by the variants below and by feature code):
 *   0: 11.5  1: 12.5  2: 13    3: 13.5  4: 14    5: 14.5  6: 15
 *   7: 15.5  8: 16.5  9: 17   10: 24   11: 28   12: 30   13: 34   14: 42
 *
 * space index map:
 *   0: 0  1: 4  2: 8  3: 12  4: 14  5: 16  6: 20  7: 22  8: 24  9: 28  10: 44  11: 60
 *
 * radii index map:
 *   0: 0  1: 7  2: 8  3: 9  4: 11  5: 13  6: 14  7: 16  8: 18  9: 999
 */
const theme: Theme = {
  breakpoints: ['48em', '64em', '80em'],

  colors: {
    text: '#E6F2F5',
    textSecondary: '#9DB2BA',
    textMuted: '#6C838C',
    textDim: '#7E959D',
    textFaint: '#536B74',
    textOnAccent: '#04242A',

    background: '#0E1416',
    chrome: '#101A1D',
    surface: '#141D21',
    surfaceRaised: '#162024',
    surfaceSubtle: '#121B1E',
    well: '#0F1719',

    chip: '#1B262B',
    chipHover: '#1E2A2F',

    border: '#22313A',
    borderSubtle: '#1C2A30',
    borderStrong: '#2E4149',
    borderInput: '#2A3940',
    borderDim: '#1E2C33',

    primary: '#0FC6D9',
    primaryHover: '#4EE1F0',
    primarySoft: 'rgba(15,198,217,0.12)',
    primaryLine: 'rgba(15,198,217,0.38)',
    primaryRing: 'rgba(15,198,217,0.16)',
    primaryWash: 'rgba(15,198,217,0.07)',

    secondary: '#AE1BD7',
    secondaryText: '#CE6BEA',
    secondarySurface: '#171522',
    secondaryBorder: '#2C2337',
    secondaryWell: '#120F1A',

    accent: '#D61DDC',
    accentText: '#E36BEE',

    success: '#3FD68C',
    successSoft: 'rgba(63,214,140,0.13)',
    successLine: 'rgba(63,214,140,0.35)',

    warning: '#F2A93B',
    warningSoft: 'rgba(242,169,59,0.07)',
    warningLine: 'rgba(242,169,59,0.30)',

    danger: '#FF5C7A',
    dangerText: '#FF8098',
    dangerSoft: 'rgba(255,92,122,0.12)',
    dangerLine: 'rgba(255,92,122,0.45)',
    dangerOn: '#2A0710',

    disabledBg: '#1A2429',
    disabledBorder: '#253238',
    disabledText: '#56707A',
  },

  fonts: {
    body: "'Instrument Sans Variable','Instrument Sans','Helvetica Neue',Arial,sans-serif",
    heading: "'Space Grotesk Variable','Space Grotesk','Helvetica Neue',Arial,sans-serif",
    monospace: "'JetBrains Mono Variable','JetBrains Mono',ui-monospace,Menlo,monospace",
  },

  fontSizes: [11.5, 12.5, 13, 13.5, 14, 14.5, 15, 15.5, 16.5, 17, 24, 28, 30, 34, 42],

  fontWeights: { body: 400, medium: 500, heading: 600, bold: 700 },

  lineHeights: { body: 1.55, lead: 1.6, heading: 1.14, display: 1.08, tight: 1.1 },

  letterSpacings: {
    display: '-0.035em',
    title: '-0.03em',
    heading: '-0.01em',
    wordmark: '-0.02em',
    caps: '0.09em',
    mono: '0.16em',
    mask: '0.18em',
  },

  space: [0, 4, 8, 12, 14, 16, 20, 22, 24, 28, 44, 60],

  radii: [0, 7, 8, 9, 11, 13, 14, 16, 18, 999],

  sizes: {
    control: 36,
    touch: 44,
    field: 48,
    action: 54,
    narrow: 520,
    retrieve: 560,
    form: 660,
    success: 680,
    wide: 1040,
  },

  shadows: {
    primary: 'inset 0 1px 0 rgba(255,255,255,0.28), 0 10px 26px -14px #0FC6D9',
    ringPrimary: '0 0 0 3px rgba(15,198,217,0.16)',
    ringDanger: '0 0 0 3px rgba(255,92,122,0.13)',
    dialog: '0 40px 90px -30px rgba(0,0,0,0.85)',
    inset: 'inset 0 1px 0 rgba(255,255,255,0.28)',
  },

  // ── Buttons ──────────────────────────────────────────────────────────────
  buttons: {
    // shared base is inlined into each variant so the `variant` prop alone is
    // enough — theme-ui does not merge a "base" key automatically.
    primary: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
      flexShrink: 0,
      px: 6,
      border: '1px solid transparent',
      borderRadius: 4,
      bg: 'primary',
      color: 'textOnAccent',
      fontFamily: 'heading',
      fontSize: 6,
      fontWeight: 'heading',
      letterSpacing: 'heading',
      lineHeight: 1,
      boxShadow: 'primary',
      cursor: 'pointer',
      transition: 'background-color .18s ease, box-shadow .18s ease, color .18s ease',
      '&:hover:not(:disabled)': { bg: 'primaryHover' },
      '&:focus-visible': { outline: 'none', boxShadow: 'ringPrimary' },
      '&:disabled': {
        bg: 'disabledBg',
        borderColor: 'disabledBorder',
        color: 'disabledText',
        boxShadow: 'none',
        cursor: 'not-allowed',
      },
    },
    secondary: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
      flexShrink: 0,
      px: 6,
      border: '1px solid',
      borderColor: 'borderStrong',
      borderRadius: 4,
      bg: 'transparent',
      color: 'text',
      fontFamily: 'body',
      fontSize: 5,
      fontWeight: 'medium',
      lineHeight: 1,
      cursor: 'pointer',
      transition: 'background-color .18s ease, border-color .18s ease',
      '&:hover:not(:disabled)': { bg: 'chip' },
      '&:focus-visible': { outline: 'none', boxShadow: 'ringPrimary' },
      '&:disabled': { color: 'disabledText', borderColor: 'disabledBorder', cursor: 'not-allowed' },
    },
    destructive: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
      flexShrink: 0,
      px: 6,
      border: '1px solid',
      borderColor: 'dangerLine',
      borderRadius: 4,
      backgroundColor: 'rgba(255,92,122,0.07)',
      color: 'danger',
      fontFamily: 'body',
      fontSize: 4,
      fontWeight: 'heading',
      lineHeight: 1,
      cursor: 'pointer',
      transition: 'background-color .18s ease',
      '&:hover:not(:disabled)': { backgroundColor: 'rgba(255,92,122,0.13)' },
      '&:focus-visible': { outline: 'none', boxShadow: 'ringDanger' },
      '&:disabled': { color: 'disabledText', borderColor: 'disabledBorder', cursor: 'not-allowed' },
    },
    destructiveSolid: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
      flexShrink: 0,
      px: 6,
      border: '1px solid transparent',
      borderRadius: 4,
      bg: 'danger',
      color: 'dangerOn',
      fontFamily: 'body',
      fontSize: 4,
      fontWeight: 'heading',
      lineHeight: 1,
      boxShadow: 'inset',
      cursor: 'pointer',
      transition: 'background-color .18s ease',
      '&:hover:not(:disabled)': { bg: 'dangerText' },
      '&:focus-visible': { outline: 'none', boxShadow: 'ringDanger' },
      '&:disabled': {
        bg: 'disabledBg',
        borderColor: 'disabledBorder',
        color: 'disabledText',
        boxShadow: 'none',
        cursor: 'not-allowed',
      },
    },
    disabled: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
      flexShrink: 0,
      px: 6,
      border: '1px solid',
      borderColor: 'disabledBorder',
      borderRadius: 4,
      bg: 'disabledBg',
      color: 'disabledText',
      fontFamily: 'heading',
      fontSize: 6,
      fontWeight: 'heading',
      lineHeight: 1,
      cursor: 'not-allowed',
    },
    inline: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
      flexShrink: 0,
      px: 3,
      border: '1px solid',
      borderColor: 'borderStrong',
      borderRadius: 2,
      bg: 'transparent',
      color: 'textSecondary',
      fontFamily: 'body',
      fontSize: 2,
      fontWeight: 'medium',
      lineHeight: 1,
      cursor: 'pointer',
      transition: 'background-color .18s ease, color .18s ease',
      '&:hover:not(:disabled)': { bg: 'chip', color: 'text' },
      '&:focus-visible': { outline: 'none', boxShadow: 'ringPrimary' },
      '&:disabled': { color: 'disabledText', cursor: 'not-allowed' },
    },
    ghost: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
      flexShrink: 0,
      px: 3,
      border: '1px solid transparent',
      borderRadius: 2,
      bg: 'chipHover',
      color: 'textSecondary',
      fontFamily: 'body',
      fontSize: 1,
      fontWeight: 'medium',
      lineHeight: 1,
      cursor: 'pointer',
      transition: 'background-color .18s ease, color .18s ease',
      '&:hover:not(:disabled)': { bg: 'chip', color: 'text' },
      '&:focus-visible': { outline: 'none', boxShadow: 'ringPrimary' },
      '&:disabled': { color: 'disabledText', cursor: 'not-allowed' },
    },
  },

  // ── Form controls ────────────────────────────────────────────────────────
  forms: {
    input: {
      width: '100%',
      minHeight: 'field',
      px: 5,
      border: '1px solid',
      borderColor: 'borderInput',
      borderRadius: 4,
      bg: 'well',
      color: 'text',
      fontFamily: 'body',
      fontSize: 4,
      lineHeight: 'body',
      outline: 'none',
      transition: 'border-color .16s ease, box-shadow .16s ease',
      '&::placeholder': { color: 'textFaint' },
      '&:focus': { borderColor: 'primary', boxShadow: 'ringPrimary' },
      '&:disabled': { bg: 'disabledBg', borderColor: 'disabledBorder', color: 'disabledText' },
    },
    inputMono: {
      width: '100%',
      minHeight: 'field',
      px: 5,
      border: '1px solid',
      borderColor: 'borderInput',
      borderRadius: 4,
      bg: 'well',
      color: 'text',
      fontFamily: 'monospace',
      fontSize: 5,
      lineHeight: 'body',
      outline: 'none',
      transition: 'border-color .16s ease, box-shadow .16s ease',
      '&::placeholder': { color: 'textFaint', letterSpacing: 0 },
      '&:focus': { borderColor: 'primary', boxShadow: 'ringPrimary' },
      '&:disabled': { bg: 'disabledBg', borderColor: 'disabledBorder', color: 'disabledText' },
    },
    inputError: {
      width: '100%',
      minHeight: 'field',
      px: 5,
      border: '1px solid',
      borderColor: 'danger',
      borderRadius: 4,
      backgroundColor: '#14161A',
      color: 'text',
      fontFamily: 'body',
      fontSize: 4,
      lineHeight: 'body',
      outline: 'none',
      boxShadow: 'ringDanger',
      '&::placeholder': { color: 'textFaint' },
      '&:focus': { borderColor: 'danger', boxShadow: 'ringDanger' },
    },
    label: {
      display: 'block',
      mb: 2,
      fontFamily: 'body',
      fontSize: 3,
      fontWeight: 'medium',
      color: 'text',
    },
  },

  // ── Cards / panels ───────────────────────────────────────────────────────
  cards: {
    surface: {
      border: '1px solid',
      borderColor: 'border',
      borderRadius: 6,
      bg: 'surface',
      p: 8,
    },
    well: {
      border: '1px solid',
      borderColor: 'borderInput',
      borderRadius: 4,
      bg: 'well',
      p: 5,
    },
    callout: {
      display: 'flex',
      alignItems: 'flex-start',
      gap: 3,
      border: '1px solid',
      borderColor: 'borderDim',
      borderRadius: 4,
      bg: 'surfaceSubtle',
      px: 5,
      py: 4,
    },
    calloutWarning: {
      display: 'flex',
      alignItems: 'flex-start',
      border: '1px solid',
      borderColor: 'warningLine',
      borderRadius: 4,
      backgroundColor: 'rgba(242,169,59,0.06)',
      px: 5,
      py: 4,
    },
    calloutDanger: {
      display: 'flex',
      alignItems: 'flex-start',
      border: '1px solid',
      borderColor: 'dangerLine',
      borderRadius: 4,
      bg: 'dangerSoft',
      px: 5,
      py: 4,
    },
  },

  // ── Badges / pills ───────────────────────────────────────────────────────
  badges: {
    active: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 2,
      px: 3,
      py: 1,
      borderRadius: 9,
      border: '1px solid',
      borderColor: 'successLine',
      bg: 'successSoft',
      color: 'success',
      fontFamily: 'body',
      fontSize: 1,
      fontWeight: 'heading',
    },
    expired: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 2,
      px: 3,
      py: 1,
      borderRadius: 9,
      border: '1px solid',
      borderColor: 'warningLine',
      backgroundColor: 'rgba(242,169,59,0.11)',
      color: 'warning',
      fontFamily: 'body',
      fontSize: 1,
      fontWeight: 'heading',
    },
    exhausted: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 2,
      px: 3,
      py: 1,
      borderRadius: 9,
      border: '1px solid',
      borderColor: 'rgba(214,29,220,0.32)',
      backgroundColor: 'rgba(214,29,220,0.11)',
      color: 'accentText',
      fontFamily: 'body',
      fontSize: 1,
      fontWeight: 'heading',
    },
    revoked: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 2,
      px: 3,
      py: 1,
      borderRadius: 9,
      border: '1px solid',
      borderColor: 'rgba(255,92,122,0.30)',
      backgroundColor: 'rgba(255,92,122,0.10)',
      color: 'danger',
      fontFamily: 'body',
      fontSize: 1,
      fontWeight: 'heading',
    },
    granted: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 2,
      px: 2,
      py: 1,
      borderRadius: 9,
      border: '1px solid transparent',
      bg: 'successSoft',
      color: 'success',
      fontFamily: 'body',
      fontSize: 1,
      fontWeight: 'heading',
    },
    refused: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 2,
      px: 2,
      py: 1,
      borderRadius: 9,
      border: '1px solid transparent',
      bg: 'dangerSoft',
      color: 'danger',
      fontFamily: 'body',
      fontSize: 1,
      fontWeight: 'heading',
    },
    mono: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 2,
      px: 3,
      py: 1,
      borderRadius: 1,
      bg: 'chip',
      color: 'textSecondary',
      fontFamily: 'monospace',
      fontSize: 1,
      fontWeight: 'body',
    },
    eyebrow: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: 2,
      pl: 2,
      pr: 3,
      py: 1,
      borderRadius: 9,
      border: '1px solid',
      borderColor: 'rgba(15,198,217,0.30)',
      bg: 'primaryWash',
      color: 'primary',
      fontFamily: 'body',
      fontSize: 0,
      fontWeight: 'heading',
      letterSpacing: 'caps',
      textTransform: 'uppercase',
    },
  },

  // ── Text variants ────────────────────────────────────────────────────────
  text: {
    display: {
      m: 0,
      fontFamily: 'heading',
      fontSize: [11, 14],
      fontWeight: 'heading',
      lineHeight: 'display',
      letterSpacing: 'display',
      color: 'text',
      textWrap: 'balance',
    },
    title: {
      m: 0,
      fontFamily: 'heading',
      fontSize: [11, 13],
      fontWeight: 'heading',
      lineHeight: 'tight',
      letterSpacing: 'title',
      color: 'text',
    },
    pageTitle: {
      m: 0,
      fontFamily: 'heading',
      fontSize: [11, 12],
      fontWeight: 'heading',
      lineHeight: 'tight',
      letterSpacing: 'title',
      color: 'text',
    },
    cardHeading: {
      m: 0,
      fontFamily: 'heading',
      fontSize: 9,
      fontWeight: 'heading',
      lineHeight: 'heading',
      letterSpacing: 'heading',
      color: 'text',
    },
    lead: {
      m: 0,
      fontFamily: 'body',
      fontSize: [6, 8],
      fontWeight: 'body',
      lineHeight: 'lead',
      color: 'textSecondary',
      textWrap: 'pretty',
    },
    body: {
      m: 0,
      fontFamily: 'body',
      fontSize: 5,
      fontWeight: 'body',
      lineHeight: 'body',
      color: 'text',
    },
    caption: {
      m: 0,
      fontFamily: 'body',
      fontSize: 1,
      fontWeight: 'body',
      lineHeight: 'body',
      color: 'textMuted',
    },
    mono: {
      m: 0,
      fontFamily: 'monospace',
      fontSize: 4,
      fontWeight: 'body',
      color: 'text',
    },
    cap: {
      m: 0,
      fontFamily: 'body',
      fontSize: 0,
      fontWeight: 'heading',
      letterSpacing: 'caps',
      textTransform: 'uppercase',
      color: 'textMuted',
    },
  },

  styles: {
    root: {
      fontFamily: 'body',
      lineHeight: 'body',
      fontWeight: 'body',
      color: 'text',
      bg: 'background',
      WebkitFontSmoothing: 'antialiased',
      backgroundImage:
        'linear-gradient(rgba(227,244,248,0.022) 1px, transparent 1px),linear-gradient(90deg, rgba(227,244,248,0.022) 1px, transparent 1px)',
      backgroundSize: '34px 34px',
      '::selection': { background: 'rgba(15,198,217,0.28)' },
      '@media (prefers-reduced-motion: reduce)': {
        '*': { animation: 'none !important', transition: 'none !important' },
      },
    },
    a: {
      color: 'primary',
      textDecoration: 'none',
      '&:hover': { color: 'primaryHover' },
    },
  },
};

export default theme;
