services:
  mongo-dev:
    image: mongo:latest
    container_name: mongo-dev
    ports:
      - '27017:27017'
    volumes:
      - mongo-data-dev:/data/db

  secret-share-server-dev:
    build:
      context: ./secret-share-server
      dockerfile: Dockerfile.dev
    container_name: secret-share-server-dev
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo-dev:27017/secret-share
    ports:
      - '5000:5000'
    volumes:
      - ./secret-share-server:/app
    depends_on:
      - mongo-dev

  secret-share-client-dev:
    build:
      context: ./secret-share-client
      dockerfile: Dockerfile.dev
    container_name: secret-share-client-dev
    environment:
      - API_URL=http://secret-share-server-dev:5000
    ports:
      - '5001:3000'
    volumes:
      - ./secret-share-client:/app
    depends_on:
      - secret-share-server-dev

volumes:
  mongo-data-dev: