services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  secret-share-server:
    build:
      context: ./secret-share-server
      dockerfile: Dockerfile
    container_name: secret-share-server
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/secret-share
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  secert-share-client:
    build:
      context: ./secret-share-client
      dockerfile: Dockerfile
    container_name: secret-share-client
    ports:
      - '8080:80'
    depends_on:
      - secret-share-server
    environment:
      - API_URL=secret-share-server:5000

volumes:
  mongo-data:
