services:
  mongo-dev:
    image: mongo:latest
    container_name: mongo-dev
    #ports: # comment and uncomment if direct mongodb data access is needed
    #  - '27017:27017'
    volumes:
      - mongo-data-dev:/data/db

  rabbitmq-dev:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-dev

  secret-share-server-dev:
    build:
      context: ./secret-share-server
      dockerfile: Dockerfile.dev
    container_name: secret-share-server-dev
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo-dev:27017/secret-share
      - RABBITMQ_HOST=rabbitmq-dev
      - CLIENT_ORIGN=http://localhost:5001
    ports:
      - '5000:5000'
    volumes:
      - ./secret-share-server:/app
      - server_node_modules:/app/node_modules
    depends_on:
      - mongo-dev

  secret-share-client-dev:
    build:
      context: ./secret-share-client
      dockerfile: Dockerfile.dev
    container_name: secret-share-client-dev
    environment:
      - API_URL=http://secret-share-server-dev:5000
      - RABBITMQ_HOST=rabbitmq-dev
    ports:
      - '5001:3000'
    volumes:
      - ./secret-share-client:/app
      - client_node_modules:/app/node_modules
    depends_on:
      - secret-share-server-dev

volumes:
  mongo-data-dev:
  client_node_modules:
  server_node_modules:
